### ISSUE TITLE
Potentially cruel and already unusual punishment for going under the speed limit

### ISSUE THREAD

**Issue by Angelanian123311** [CosmicPikachu001/s3air-vsmetalsonic#1]
When the boss fight starts, the camera rises automatically, and too fast. If you don't get to the gravity-swapping transporter in time, you'll die from a pit. Also, the control panel on the other side of the transporter continues to explode rapidly and noisily after defeating Metal Sonic.
Most people don't seem to recognize these, but still, I hope this can be fixed somehow.

**Comment by RoyalGuard1991** [comment]
I second fixing the issues listed above.

The automatic upwards screen scroll the moment the boss music starts really isn't necessary, and it more so leads to cheap deaths than anything else. Camera adjustments are probably better triggered the moment the player exits the transporter, or just before the boss spawns in, if at all possible.

The exploding control panel after the boss ends is visually excessive and extremely loud and obnoxious with its stacking sound effects. I'd very much appreciate it being toned down, and preferably the effect not being looped infinitely. The control panel only needs to explode for a few seconds and stop.

**Comment by CosmicPikachu001** [comment]
I'm not entirely sure on how I could fix the control panel issue, but I can definitely fix the camera issue. Will be fixed for the next update.

**Comment by CosmicPikachu001** [comment]
Update out, camera issue fixed.
