### ISSUE TITLE
"Bomb Attack" Phase Doesn't Consider Characters With Good Vertical Movement Options

### ISSUE THREAD

**Issue by RoyalGuard1991** [CosmicPikachu001/s3air-vsmetalsonic#2]
When Metal Sonic is in his "Bomb Attack" phase, characters such as Tails, Knuckles, and various Extra Slot characters with good vertical movement options can trivialize it by camping above where his bombs spawn.

![Fly Bombs](https://github.com/CosmicPikachu001/s3air-vsmetalsonic/assets/117999968/b3a3caf7-ca1f-43d0-94a5-110cb6f544e3)

Perhaps it would be a good idea to not allow the screen to scroll vertically once the boss starts? This not only stops characters from camping above the bomb spawns, but also makes sure the player's immersion isn't breaking from seeing bombs magically poofing into existence if they scroll the screen upwards.

**Comment by CosmicPikachu001** [comment]
I'll fix it for the next update.

**Comment by CosmicPikachu001** [comment]
Update is out, issue fixed.
